apiVersion: v1
kind: Secret
metadata:
  name: spark-secret
type: Opaque
stringData:
  spark-defaults.conf: |
    spark.hadoop.javax.jdo.option.ConnectionPassword {{.Values.config.sparkDefaultConfig.spark_hadoop_javax_jdo_option_ConnectionPassword}}
    spark.hadoop.javax.jdo.option.ConnectionUserName {{.Values.config.sparkDefaultConfig.spark_hadoop_javax_jdo_option_ConnectionUserName}}
    spark.hadoop.fs.s3a.access.key {{.Values.config.sparkDefaultConfig.spark_hadoop_fs_s3a_access_key}}
    spark.hadoop.fs.s3a.secret.key {{.Values.config.sparkDefaultConfig.spark_hadoop_fs_s3a_secret_key}}