kind: Service
apiVersion: v1
metadata:
  name: spark-master-headless
spec:
  ports:
  clusterIP: None
  selector:
    {{- include "helm.selectorLabelsMaster" . | nindent 4 }}

---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
    - port: 10001
      targetPort: 10001
      name: thrift
  selector:
    {{- include "helm.selectorLabelsMaster" . | nindent 4 }}
