kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      hostname: spark-master-hostname
      subdomain: spark-master-headless
      # initContainers:
      # - name: init-myservice
      #   image: busybox:1.28
      #   volumeMounts:
      #   # - mountPath: /opt/spark/conf-init
      #   #   name: emptydir
      #   - mountPath: /opt/spark/conf-configMap
      #     name: test-volume
      #     readOnly: false
      #   - mountPath: /opt/spark/conf-secret
      #     name: test-secret
      #     readOnly: false 
      #   command: ['sh', '-c', "cat /opt/spark/conf-configMap/spark-defaults.conf /opt/spark/conf-secret/spark-defaults.conf  >> /opt/spark/conf-init/spark-defaults.conf;"]
      containers:
        - name: spark-master
          volumeMounts:
          # - mountPath: /opt/spark/conf-init
          #   name: emptydir
          - mountPath: /opt/spark/conf-configMap
            name: config-volume
          - mountPath: /opt/spark/conf-secret
            name: secret-volume
            readOnly: true
          image: spark3n:v9
          command: ["/bin/sh","-c"]
          args: ["cat /opt/spark/conf-configMap/spark-defaults.conf /opt/spark/conf-secret/spark-defaults.conf  >> /opt/spark/conf/spark-defaults.conf; /opt/spark/docker-configs/spark-thrift;/opt/spark/docker-configs/spark-master;"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 1
              memory: 1200Mi
      volumes:
      - name: config-volume
        configMap:
          name: spark-default-config
      - name: secret-volume
        secret:
          secretName: spark-secret
      # - name: emptydir
      #   emptyDir: {}
