#!/bin/bash
. /opt/spark/docker-configs/common.sh
if ! getent hosts spark-master; then 
sleep 5 
exit 0 
fi
/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 --memory 2g  --cores 2 --webui-port 8081
